#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/git/init.zsh"
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/python/init.zsh"
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/node/init.zsh"
  source "${ZDOTDIR:-$HOME}/.zprezto/modules/fasd/init.zsh"
fi

# Customize to your needs...

export WORKON_HOME="$HOME/.envs"
source "/usr/local/bin/virtualenvwrapper.sh"
alias ez='. "/home/najam/z.sh"'
alias enableshell='. /home/najam/webapps/dubizzle/shell.sh'

export TERM=xterm-256color
export PYTHONSTARTUP=~/.pythonrc
export LANG="en_US.utf8"
export SHELL="/bin/zsh"

#setopt EXTENDED_GLOB
#for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
#  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
#done


# if [ -n "$DISPLAY" -a "$TERM" == "xterm" ]; then
#    export TERM=xterm-256color
# fi
export ES_HOME="/usr/local/src/elasticsearch-0.20.2/"
